package com.drivewealth.dbproxy.entity;


import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.*;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "GrpcPoc")
@JsonInclude(JsonInclude.Include.NON_NULL)
public class GrpcPocDTO {


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Getter
    @Setter
    @JsonProperty("id")
    String id;

    @DynamoDBAttribute
    @Getter
    @Setter
    @JsonProperty("name")
    @JsonInclude(JsonInclude.Include.NON_DEFAULT)
    String name;

    @DynamoDBAttribute
    @Getter
    @Setter
    @JsonProperty("contact")
    @JsonInclude(JsonInclude.Include.NON_DEFAULT)
    String contact;

    @DynamoDBAttribute
    @Getter
    @Setter
    @JsonProperty("createdAt")
    @JsonInclude(JsonInclude.Include.NON_DEFAULT)
    String createdAt;
}
